### ISSUE TITLE
How to access local installed Pageonex to download files?

### ISSUE THREAD

**Issue by numeroteca** [numeroteca/colorcorrupcion#2]
I am trying to download multiple files in a local installed Pageonex. I have problems reusing this script https://github.com/numeroteca/colorcorrupcion/blob/master/wget_raw.sh but with http://localhost:3000 as domain. How to enable access?

I get this error:
```
--2021-09-02 01:06:32--  http://localhost:3000/corrupcion-spain-enero-2013/raw.json
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-02 01:06:32 ERROR 404: Not Found.
```
Ideas for this, @rporres?

**Comment by numeroteca** [comment]
There was a mistake in the path, that has been fixed. Now the problem is related to Unauthorized access, how to fix it?

```
--2021-09-02 16:17:04--  http://localhost:3000/numeroteca/corrupcion-spain-enero-2013/raw.json
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 401 Unauthorized
```

**Comment by rporres** [comment]
that's weird, it works in pageonex.com
```
$ curl -s http://pageonex.com/numeroteca/corrupcion-spain-enero-2013/raw.json | jq | head
{
  "areas": [
    {
      "areas_id": 725,
      "user_name": "numeroteca",
      "code_text": "CiU",
      "publication_date": "2013-01-15",
      "media_name": "El Mundo",
      "media_country": "Spain",
      "area_x1": 1,
```
and I'm not authenticated

**Comment by rporres** [comment]
Do you get anything in the logs that can help?

**Comment by numeroteca** [comment]
Ups, sorry. I modified the script (https://github.com/numeroteca/colorcorrupcion/commit/01dc015718525331b2ce5feb05115f3bb4c50526#diff-2c9cf19446bfd1a9d263429fe56621b175e2749c09c6bfa51a9652646515b7a7) to change from localhost:3000 to pageonex.com to make it work.
The problem is just related to authorization of access from my local computer to the Pageonex install in the docker.

**Comment by rporres** [comment]
That was my question. Do you have any logs about it?

**Comment by numeroteca** [comment]
Ups, it's bee a while, I still need this fix.
When I try 
`wget -O colorcorrupcion-x.json http://localhost:3000/numeroteca/corrupcion-spain-enero-2013/raw.json`

I get

```
--2021-11-07 12:58:15--  http://localhost:3000/numeroteca/corrupcion-spain-enero-2013/raw.json
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```

I don't see much in the docker logs:
```
$ docker logs pageonex
[1] Puma starting in cluster mode...
[1] * Version 3.11.4 (ruby 1.9.3-p551), codename: Love Song
[1] * Min threads: 5, max threads: 5
[1] * Environment: production
[1] * Process workers: 2
[1] * Preloading application
[1] * Listening on tcp://0.0.0.0:3000
[1] Use Ctrl-C to stop
[1] - Worker 0 (pid: 12) booted, phase: 0
[1] - Worker 1 (pid: 16) booted, phase: 0
```

How do I have to do to look in the RoR docker logs?

**Comment by rporres** [comment]
I don't know how that works... maybe setting the environment to something different forces it to get more logs...

**Comment by numeroteca** [comment]
@skotperez sugiere acceder por SSH al docker container. Quizás desde dentro no de problemas de permisos ¿cómo se accede a ese container? Así podria lanzar el script desde ahí para pillar los datos.

He mirado esto https://adamtheautomator.com/ssh-into-docker-container/
pero añadiedo `i -t pageonex` al [script de lanzamiento](https://github.com/montera34/pageonex/wiki/How-to-install-Pageonex-with-Docker-against-and-external-database) no me funciona:

```
docker run -d --name pageonex \
  -p 3000:3000 \
  --env-file env \
  -v /home/numeroteca/local-pageonex/tmp:/workspace/tmp \
  -v /home/numeroteca/local-pageonex/assets/images/kiosko:/workspace/app/assets/images/kiosko \
  -v /home/numeroteca/local-pageonex/assets/images/threads:/workspace/app/assets/images/threads \
  pageonex/pageonex:latest  i -t pageonex 

```

**Comment by numeroteca** [comment]
Según este otro es más sencillo https://phoenixnap.com/kb/how-to-ssh-into-docker-container:

```
$ sudo docker inspect -f "{{ .NetworkSettings.IPAddress }}" pageonex
[sudo] password for numeroteca: 
172.17.0.2
```

```
$ ping -c 3 172.17.0.2
PING 172.17.0.2 (172.17.0.2) 56(84) bytes of data.
64 bytes from 172.17.0.2: icmp_seq=1 ttl=64 time=0.090 ms
64 bytes from 172.17.0.2: icmp_seq=2 ttl=64 time=0.071 ms
64 bytes from 172.17.0.2: icmp_seq=3 ttl=64 time=0.078 ms
```

Y ahora intento conectarme:
```
ssh root@172.17.0.2
ssh: connect to host 172.17.0.2 port 22: Connection refused
```

Intento con el puerto 3000 pero no me deja:
```
$ ssh root@172.17.0.2:3000
ssh: Could not resolve hostname 172.17.0.2:3000: Name or service not known
```

```
$ ssh -p 3000 root@172.17.0.2
kex_exchange_identification: Connection closed by remote host
Connection closed by 172.17.0.2 port 3000
```

¿ideas?

**Comment by numeroteca** [comment]
@rporres we found that the problem is not related to docker access, but to the access to the raw.json file. It was reported by@martgnz and solved time ago: https://github.com/montera34/pageonex/issues/228 but the docker image does not have the change yet, I think. In fact the pageonex.com version does not have the upgraded version :-/

The script should have included "raw" among its exceptions (
https://github.com/montera34/pageonex/blob/master/app/controllers/threads_controller.rb#L5)
`before_filter :authenticate_user!, :except => ["index", "by_username", "search_by_category", "search", "export"]`
As it has been already changed in the repsository.

So, we are ready for another docker image @rporres when possible. I can also try to do it, if feasible!

**Comment by numeroteca** [comment]
A new docker container image can be manually build (with `make docker-build`) or every time a version is tagged in this repository. See the list of pageonex docker images at https://hub.docker.com/r/pageonex/pageonex/tags

If you need to stop the container (because you need to restart the container image: docker stop pageonex

If you need to update the docker container image: docker pull pageonex/pageonex

In this case @rporres created a docker image manually and uploaded to the docker repo.

![Screenshot from 2021-12-07 11-56-01](https://user-images.githubusercontent.com/1223722/145016665-af8cc95e-2cd5-4302-a33f-21a6365422b3.png)

I tested locally... and this works! There is no need anymore to log in to download the raw.json area file.
